version: '3.8'

services:
  devbox:
    platform: linux/amd64
    # image: ubuntu:20.04
    build: .
    volumes:
      - .:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    command: /bin/bash
